version = 0.1.0
java_name = cascara.test.common.junit
maven_name = cascara-test-common-junit
group = io.github.qishr
title = Cascara Testing Shared Classes for JUnit
description = Cascara Testing Shared Classes for JUnit
url = https://qishr.github.io/cascara/test
scm_url = https://github.com/qishr/cascara-test-common-junit
scm_conn = scm:git:https://github.com/qishr/cascara-test-common-junit.git
scm_dev_conn = scm:git:https://github.com/qishr/cascara-test-common-junit.git

cascara_version = 0.11.0
org.gradle.configuration-cache = false


